export const routes = {
  home: "/",
  shop: "/shop",
  category: (slug: string) => `/shop/${slug}`,
  product: (slug: string) => `/products/${slug}`,
  about: "/about",
  contact: "/contact",
  stockists: "/stockists",
  faq: "/faq",
  cart: "/cart",
  checkout: "/checkout",
  privacy: "/privacy",
  terms: "/terms",
  returns: "/returns",
} as const;
